# Project information
site_name: 'FDU-MSC 论坛'
site_description: '技术分享、讨论与学习'
site_author: 'FDU-MSC'
site_url: 'https://fdu-msc.github.io/forum'
site_dir: 'docs'
docs_dir: 'content'
edit_uri: 'edit/master/content'

# Repository
repo_name: 'fdu-msc/forum'
repo_url: 'https://github.com/fdu-msc/forum'

# Copyright
copyright: 'Built by <a href="http://github.com/fdu-msc">FDU-MSC</a> &copy; 2019'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  custom_dir: 'custom/'
  favicon: '_static/assets/logo.jpeg'
  palette:
    primary: 'Black'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'code'
  feature:
    tabs: true

# # Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/fdu-msc'
    - type: 'quote-left'
      link: 'https://fdu-msc.github.io/forum'
    - type: 'forum'
      link: 'https://github.com/fdu-msc/forum'

extra_css:
  - '_static/css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css'

extra_javascript:
  - '_static/js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/contrib/auto-render.min.js'

# Google Analytics
google_analytics:
  - 'UA-149024530-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
  - 主页:
    - 欢迎: index.md
    - 通知: announcement.md
    - 如何贡献: contribute.md
    - Mkdocs 简介: mkdocs-intro.md
    - 入站仪式: welcome.md
  - 建设本站: build/index.md
  - 课程学习:
    - 计算机: courses/index.md
    - 大数据: courses/index.md
    - 软工: courses/index.md
  - 技术学习:
    - 前端开发: technology/index.md
    - 后端开发: technology/index.md
    - 深度学习: technology/index.md
  - 资源分享:
    - Markdown: share/markdown.md
    - GitHub: share/github.md
    - 工具推荐:
      - 全平台: share/tools/ubiquitous.md
      - Linux: share/tools/linux.md
      - Windows: share/tools/windows.md
      - MacOS: share/tools/macos.md
  - 刷题:
    - 每周一题:
       - 第三周: oj/9-25.md
       - 第五周: oj/10-13.md

